// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"database/sql"
	"time"
)

type Block struct {
	Difficulty       sql.NullString `json:"difficulty"`
	ExtraData        sql.NullString `json:"extra_data"`
	GasLimit         sql.NullInt64  `json:"gas_limit"`
	GasUsed          sql.NullInt64  `json:"gas_used"`
	Hash             sql.NullString `json:"hash"`
	LogsBloom        sql.NullString `json:"logs_bloom"`
	Miner            sql.NullString `json:"miner"`
	MixHash          sql.NullString `json:"mix_hash"`
	Nonce            sql.NullString `json:"nonce"`
	Number           int64          `json:"number"`
	ParentHash       sql.NullString `json:"parent_hash"`
	ReceiptsRoot     sql.NullString `json:"receipts_root"`
	Sha3Uncles       sql.NullString `json:"sha3_uncles"`
	Size             sql.NullInt64  `json:"size"`
	StateRoot        sql.NullString `json:"state_root"`
	Timestamp        sql.NullInt64  `json:"timestamp"`
	TotalDifficulty  sql.NullString `json:"total_difficulty"`
	TransactionsRoot sql.NullString `json:"transactions_root"`
	TransactionCount int16          `json:"transaction_count"`
	CreatedTimestamp time.Time      `json:"created_timestamp"`
}
